<?php

namespace AppBundle\Repository;

/**
 * PurchaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllWithProduct()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('pu')
            ->from('AppBundle:Purchase','pu')
            ;
        return $qb->getQuery()->getResult();
    }
}
